@startuml

title Netotiate Proof

actor "Steward" as S
actor "Goverment" as G
actor "Holder" as H 
actor "Verifier" as V


participant "indy-node" as I

note over S, V
공통로직
- Open pool handles
- Create wallets
- Open wallets
end note

== DID, DID document 생성 ==
S -> S : createAndStoreMyDid
G -> G : createAndStoreMyDid
G --> S : Goverment가 DID 및 인증키를 \nSteward에게 전달하며 Endorser 자격등록 요청
S -> S : buildNymRequest
S -> I : signAndSubmitRequest
I -> S : Request result as JSON

== Schema 생성 == 
G -> G : issuerCreateSchema 
G -> G : buildSchemaRequest 
G -> I : signAndSubmitRequest
I -> G : Request result as JSON

==  Credential definition 생성 ==
G -> G : buildGetSchemaRequest 
G -> I : submitRequest
I -> G : Request result as JSON 
G -> G : parseGetSchemaResponse 
G -> G : issuerCreateAndStoreCredentialDef 
G -> G : buildCredDefRequest 
G -> I : signAndSubmitRequest
I -> G : Request result as JSON

== Issuer Credential == 
H --> G : Credential offer 요청 
G -> G : issuerCreateCredentialOffer 
G --> H : Credential offer 전달 
H -> H : proverCreateMasterSecret 
H -> H : buildGetCredDefRequest 
H -> I : submitRequest 
I -> H : Request result as JSON 
H -> H : parseGetCredDefResponse 
H -> H : proverCreateCredentialReq 
H --> G : VC 발급 요청
G -> G : issuerCreateCredential 
G --> H : Credential 전달 
H -> H : proverStoreCredential


== Netotiate Proof== 
V -> V : createProofReq
V --> H : proofRequest 전달 
H -> H : CredentialsSearchForProofReq.open
H -> H : credentialsSearch.close
H -> I : getSchemaFromLedger 
I -> H : Request result as JSON
H -> I : getCredDefFromLedger
I -> H : Request result as JSON
H -> H : proverCreateProof 
H --> V : proof 전달 
V -> V : checkAttribute
V -> I : getSchemaFromLedger  
V -> I : getCredDefFromLedger 
V -> V : verifierVerifyProof 


@enduml